items:
  enableamountlimit: true
  silentamountlimit: true
  maxspawnamount: 20
tpa:
  expiration: 30
broadcasting:
  effectId: 42069
  # In Milliseconds (1000 for 1 second)
  defaultBroadcastDuration: 5000
  timeLimit: 25000
  repeatingInterval: 30000
  repeatingDuration: 6000
  repeatingMessages:
    - SupahBroadcasto
    - This is bla b
    - a a a 
afkchecker:
  enabled: true
  timeout: 600
  # announceAFK will just tell everyone when someone goes afk. kickAFK will get kick players that go afk.
  announceAFK: true
  kickAFK: false
teleportation:
  # Delay in seconds before players can teleport (through warp, tpa, etc)
  delay: 5
  cancelOnMove: true
  cancelOnDamage: true
connections:
  joinMessages: true
  leaveMessages: true
